services:
  mongo-order:
    image: 'mongo:8.0.15-noble'
    environment:
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ping: 1})' --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./mongodb-data:/data/db
  flyway:
    image: flyway/flyway:11.14.0-mongo
    entrypoint: ["flyway", "migrate"]
    depends_on:
      mongo-order:
        condition: service_healthy
    volumes:
      - ./flyway/flyway.toml:/flyway/conf/flyway.toml
      - ./flyway/migrations:/migrations
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7081
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 2s
      retries: 3
    command: ["start-dev", "--http-port", "7081", "--import-realm"]
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    ports:
      - "7081:7081"
  pact-stub-server:
    image: pactfoundation/pact-stub-server
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 2s
      retries: 3
    volumes:
      - ./target/pacts:/app/pacts
    command:
      - '-p'
      - '8080'
      - '-d'
      - '/app/pacts'
      - '-l'
      - 'info'
    ports:
      - "8381:8080"
