server:
  port: 8380
shop:
  clientId: shop
stock:
  url: http://localhost:8381
spring:
  application:
    name: order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7081/realms/order-dev
      client:
        registration:
          shop:
            client-id: ${shop.clientId}
            authorization-grant-type: client_credentials
        provider:
          shop:
            token-uri: http://localhost:7081/realms/order-dev/protocol/openid-connect/token
  flyway:
    enabled: true
    locations: classpath:db/migration
    mongodb:
      uri: mongodb://localhost:27017/your_database
